#!/usr/bin/env node
const childProcessExec = require('child_process').exec;
const util = require('util');
const fs = require('fs')
const path = require('path')
const exec = util.promisify(childProcessExec);
const __dir = path.join(__dirname,"../../")

isUpdateAddonsjson();

Date.prototype.now = function () {
    function pad(number, length) {

        let str = '' + number;
        while (str.length < length) {
            str = '0' + str;
        }
    
        return str;
    
    }
    let yyyy = (this.getYear()-100).toString();
    let MM = pad(this.getMonth() + 1,2);
    let dd = pad(this.getDate(), 2);
    let hour = this.getHours()
    hour = hour == 0 ? 24 : hour
    hour = hour > 12 ? hour -12 : hour
    let hh = pad(hour, 2);
    let mm = pad(this.getMinutes(), 2)
    return yyyy + MM + dd+  hh + mm;
};

async function isUpdateAddonsjson(){
    let i = 0
    let {stdout} = await exec('git show -- addons.json')
    if(stdout){
        let pre = await exec('git show HEAD~:addons.json')
        let prejson = JSON.parse(pre.stdout).reduce((obj, item) => ({...obj, [item.name]: item}), {})
        // let pre = await exec('cat addons.json')

        // require(__dir+'/addons.json').forEach(async (postObj) => {
        let post = await require(__dir+'/addons.json')
        // console.log(post)
        for(postObj of post){
            let preObj = prejson[postObj.name]
            if(!preObj)
                console.log(postObj.name + ' is new addon')
            else if(preObj.fileVersion === postObj.fileVersion)
                continue
            else
                console.log(postObj.name + ' is updalable')

            if(!preObj)
                console.log('new ' + postObj.fileVersion)
            else if(!isFileVersionDiffrence(preObj.fileVersion,postObj.fileVersion))
                continue
            else
                console.log(preObj.fileVersion + ' -> ' + postObj.fileVersion)
            
            await uploadIpf(postObj)
        }
            // });
    }
}

async function uploadIpf(postObj){
    let fileName = `${postObj.file}-${postObj.fileVersion}.ipf`
    let findFile = await exec(`find -name ${postObj.file}.lua`)
    if(!findFile.stdout){
        console.log(`not found ${postObj.file}.lua`)
        return
    }
    let dirPath = path.join(__dir,findFile.stdout,'..')
    let releaseTag = postObj.releaseTag
    try{
        await exec('mkdir ReleasedIPF')
    }catch{}
    let depth = 0
    let tempDirPath = path.join(__dir,'ReleasedIPF',postObj.file)
    try{
        if(dirPath.includes('\\src')){
            let {srcDirPath , _depth} = getSrcDirPath(dirPath)
            dirPath = srcDirPath
            depth = _depth
        }
        await exec(`cp -r ${dirPath} ${tempDirPath}`)
        console.log(`Packaging ${fileName}`)
        if(depth > 1){
            await exec(`rm -rf ${tempDirPath}`)
            return console.error('Error : Unsupported directory structure')
        }else{        
            await exec(`tpIpfTool ${tempDirPath}${(depth == 1)?'/':''}`)
        }
        await exec(`rm -rf ${tempDirPath}`)
    }catch{
        await exec(`rm -rf ${tempDirPath}`)
    }
    console.log('Packaging Success')
    await exec(`mv -f  _p${(new Date()).now()}* ReleasedIPF\\${fileName}`)
    console.log(`Uploading : ${fileName}. Tag : ${releaseTag}`)
    try{
        await exec(`ghr ${releaseTag} ${fileName}`)
    }catch{
        return console.log('Error : Cannot upload ' + fileName)
    }
    console.log(`${fileName} move to ReleasedIPF`)
    console.log(`UploadIPF is complite`)
    return true
}

function isFileVersionDiffrence(preVer,postVer){
    let preVerArr = preVer.substr(1).split('.')
    let postVerArr = postVer.substr(1).split('.')
    for(let i = 0; i < preVerArr.length; i++){
        if(Number(preVerArr[i]) > Number(postVerArr[i]))
            return false
        else if (Number(preVerArr[i]) < Number(postVerArr[i]))
            return true
    }
    return false
}

function getSrcDirPath(dirPath){
    let arr = dirPath.split('\\src')
    while(arr.length != 1){
        arr.shift()
    }
    let depth = arr[0].match(/\\/gm).length
    return {srcDirPath : path.join(dirPath,"\\..".repeat(depth)), _depth : depth}
}
